typography_spectrum: 0.4291310061234981
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.5970750199630857
  lightness: 0.21818454167805612
  saturation: 0.7899303121957928
  rhythmicContrast: 0.21402363060042262
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.8387582686264068
analytics:
  google: null
  facebook: null
  twitter: null
name: Founders Network
cta:
  domain: null
  bucket: null
  version: null
favicon: null
purpose: []
